// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvDuWPFtv9Ql91kFH01IrXJvjqg-I-PUQ',
    appId: '1:125108668086:web:56415aedee37facd3b0817',
    messagingSenderId: '125108668086',
    projectId: 'jitutor',
    authDomain: 'jitutor.firebaseapp.com',
    storageBucket: 'jitutor.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOJhJ7d0tEMcP63fteFKYIrTIYF1kORHI',
    appId: '1:125108668086:android:aea3dbc23e20a10f3b0817',
    messagingSenderId: '125108668086',
    projectId: 'jitutor',
    storageBucket: 'jitutor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEMNO9Rc87WUx1eCJIDkGr4EB8VksL_hE',
    appId: '1:125108668086:ios:312b597e4e5b11ae3b0817',
    messagingSenderId: '125108668086',
    projectId: 'jitutor',
    storageBucket: 'jitutor.appspot.com',
    iosClientId: '125108668086-o2166f0iavi29igcbquutvnem9qmd49a.apps.googleusercontent.com',
    iosBundleId: 'com.jitutor.jitutorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEMNO9Rc87WUx1eCJIDkGr4EB8VksL_hE',
    appId: '1:125108668086:ios:312b597e4e5b11ae3b0817',
    messagingSenderId: '125108668086',
    projectId: 'jitutor',
    storageBucket: 'jitutor.appspot.com',
    iosClientId: '125108668086-o2166f0iavi29igcbquutvnem9qmd49a.apps.googleusercontent.com',
    iosBundleId: 'com.jitutor.jitutorapp',
  );
}
